function Set-Thing {
    <#
    .SYNOPSIS
        Calls `POST /things`.

    .DESCRIPTION
        Calls the `putThing` operation (`POST /things`).

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Set-Thing

        Calls `POST /things`.

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: `putThing` (`POST /things`)
    #>
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    param(
        [Parameter()]
        [switch]
        $Raw
    )

    process {
        # Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        $tcsParameterMap = @{}
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['putThing']
            Cmdlet    = $PSCmdlet
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        $tcsTarget = '/things'
        foreach ($tcsKey in @($tcsValues['path'].Keys)) {
            $tcsTarget = $tcsTarget.Replace('{' + $tcsKey + '}', [string]$tcsValues['path'][$tcsKey])
        }
        if (-not $PSCmdlet.ShouldProcess($tcsTarget, 'POST')) {
            return
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
