function Get-StockItem {
    <#
    .SYNOPSIS
        Get an item from stock

    .DESCRIPTION
        Get an item from stock

        Calls the `getStockItem` operation (`GET /items/{itemId}`).

    .PARAMETER ItemId
        The `itemId` path parameter.

    .PARAMETER DebugQuery
        Adds debug output.

    .PARAMETER RawQuery
        The `Raw` query parameter.

    .PARAMETER UserId
        The `user_id` query parameter.

    .PARAMETER UserIdQuery
        The `userId` query parameter.

    .PARAMETER Filter
        The `$filter` query parameter.

    .PARAMETER PageSize
        The `page[size]` query parameter.

    .PARAMETER XRequestId
        The `X-Request-Id` header parameter.

    .PARAMETER HostHeader
        The `Host` header parameter.

    .PARAMETER XStrict
        The `X-Strict` header parameter.

    .PARAMETER SessionId
        The `session_id` cookie parameter.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-StockItem -ItemId 'example' -XRequestId 'example' -XStrict $true

        Calls `GET /items/{itemId}` with example values for the required parameters.

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: `getStockItem` (`GET /items/{itemId}`)
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string]
        $ItemId,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [switch]
        $DebugQuery,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [string]
        $RawQuery,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [Alias('user_id')]
        [string]
        $UserId,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [string]
        $UserIdQuery,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [string]
        $Filter,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [long]
        $PageSize,

        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [Alias('X-Request-Id')]
        [string]
        $XRequestId,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [Alias('Host')]
        [string]
        $HostHeader,

        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [Alias('X-Strict')]
        [bool]
        $XStrict,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [Alias('session_id')]
        [string]
        $SessionId,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        # Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        $tcsParameterMap = @{
            'ItemId'      = @('path', 'itemId')
            'DebugQuery'  = @('query', 'debug')
            'RawQuery'    = @('query', 'Raw')
            'UserId'      = @('query', 'user_id')
            'UserIdQuery' = @('query', 'userId')
            'Filter'      = @('query', '$filter')
            'PageSize'    = @('query', 'page[size]')
            'XRequestId'  = @('header', 'X-Request-Id')
            'HostHeader'  = @('header', 'Host')
            'XStrict'     = @('header', 'X-Strict')
            'SessionId'   = @('cookie', 'session_id')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['getStockItem']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['PathParameters'] = $tcsValues['path']
        $tcsRequest['QueryParameters'] = $tcsValues['query']
        $tcsRequest['HeaderParameters'] = $tcsValues['header']
        $tcsRequest['CookieParameters'] = $tcsValues['cookie']
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
