function Update-StockItem {
    <#
    .SYNOPSIS
        Calls PATCH /items/{itemId}.

    .DESCRIPTION
        Calls the 'updateStockItem' operation (PATCH /items/{itemId}).

    .PARAMETER ItemId
        The 'itemId' path parameter.

    .PARAMETER ItemIdBody
        The 'itemId' property of the request body.

    .PARAMETER Name
        The 'name' property of the request body.

    .PARAMETER DebugBody
        The 'debug' property of the request body.

    .PARAMETER Body
        The whole request body (for example a hashtable or an object read from a file), instead of the individual body parameters.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Update-StockItem -ItemId 'example' -Name 'example'

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: updateStockItem (PATCH /items/{itemId})
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
    #>
    [CmdletBinding(DefaultParameterSetName = 'Parameters', SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    param(
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string]
        $ItemId,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [string]
        $ItemIdBody,

        [Parameter(Mandatory = $true, ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [string]
        $Name,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [switch]
        $DebugBody,

        [Parameter(Mandatory = $true, ParameterSetName = 'Body')]
        [object]
        $Body,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{
            'ItemId'     = @('path', 'itemId')
            'ItemIdBody' = @('body', 'itemId')
            'Name'       = @('body', 'name')
            'DebugBody'  = @('body', 'debug')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['updateStockItem']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['PathParameters'] = $tcsValues['path']
        if ($PSCmdlet.ParameterSetName -eq 'Body') {
            $tcsRequest['Body'] = $Body
        }
        else {
            $tcsRequest['Body'] = $tcsValues['body']
        }
        $tcsRequest['ContentType'] = 'application/json'
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        $tcsTarget = '/items/{itemId}'
        foreach ($tcsKey in @($tcsValues['path'].Keys)) {
            $tcsTarget = $tcsTarget.Replace('{' + $tcsKey + '}', [string]$tcsValues['path'][$tcsKey])
        }
        if (-not $PSCmdlet.ShouldProcess($tcsTarget, 'PATCH')) {
            return
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
