function Get-PetStorePetById {
    <#
    .SYNOPSIS
        Info for a specific pet

    .DESCRIPTION
        Info for a specific pet

        Calls the `showPetById` operation (`GET /pets/{petId}`).

    .PARAMETER PetId
        The id of the pet to retrieve.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-PetStorePetById -PetId 'example'

        Calls `GET /pets/{petId}` with example values for the required parameters.

    .OUTPUTS
        PetStore.Pet

    .NOTES
        Operation: `showPetById` (`GET /pets/{petId}`)

    .LINK
        https://docs.example.com/pets
    #>
    [CmdletBinding()]
    [OutputType('PetStore.Pet')]
    param(
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [string]
        $PetId,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        # Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        $tcsParameterMap = @{
            'PetId' = @('path', 'petId')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['showPetById']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['PathParameters'] = $tcsValues['path']
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
