function Get-PetStorePetPhoto {
    <#
    .SYNOPSIS
        Download the photo of a pet

    .DESCRIPTION
        Download the photo of a pet

        Calls the 'getPetPhoto' operation (GET /pets/{petId}/photo).

    .PARAMETER PetId
        The 'petId' path parameter.

    .PARAMETER OutFile
        Saves the response content to this file and returns the file.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-PetStorePetPhoto -PetId 'example'

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: getPetPhoto (GET /pets/{petId}/photo)
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [string]
        $PetId,

        [Parameter()]
        [string]
        $OutFile,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{
            'PetId' = @('path', 'petId')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['getPetPhoto']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['PathParameters'] = $tcsValues['path']
        if ($PSBoundParameters.ContainsKey('OutFile')) {
            $tcsRequest['OutFile'] = $OutFile
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
