function Get-PetStorePet {
    <#
    .SYNOPSIS
        List all pets

    .DESCRIPTION
        Returns the pets in the store.
        Results are paged.

        Calls the 'listPets' operation (GET /pets).

    .PARAMETER Limit
        How many items to return at one time (max 100).

    .PARAMETER Tags
        Tags to filter by.

    .PARAMETER All
        Follows the next-page links and returns the items of every page.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-PetStorePet

    .OUTPUTS
        PetStore.Pet

    .NOTES
        Operation: listPets (GET /pets)
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        This command lists or searches: it can return more than one object.
    #>
    [CmdletBinding()]
    [OutputType('PetStore.Pet')]
    param(
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateRange(1, 100)]
        [int]
        $Limit,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [string[]]
        $Tags,

        [Parameter()]
        [switch]
        $All,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{
            'Limit' = @('query', 'limit')
            'Tags'  = @('query', 'tags')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['listPets']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['QueryParameters'] = $tcsValues['query']
        if ($PSBoundParameters.ContainsKey('All')) {
            $tcsRequest['All'] = $All
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
