function New-PetStorePet {
    <#
    .SYNOPSIS
        Create a pet

    .DESCRIPTION
        Create a pet

        Calls the 'createPets' operation (POST /pets).

    .PARAMETER Name
        The name of the pet.

    .PARAMETER Tag
        A tag for the pet.

    .PARAMETER Status
        The pet status in the store.

    .PARAMETER Body
        The whole request body (for example a hashtable or an object read from a file), instead of the individual body parameters.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        New-PetStorePet -Name 'example'

    .OUTPUTS
        PetStore.Pet

    .NOTES
        Operation: createPets (POST /pets)
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
    #>
    [CmdletBinding(DefaultParameterSetName = 'Parameters', SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    [OutputType('PetStore.Pet')]
    param(
        [Parameter(Mandatory = $true, ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [ValidateLength(1, 50)]
        [string]
        $Name,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [AllowNull()]
        [string]
        $Tag,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [ValidateSet('available', 'pending', 'sold')]
        [string]
        $Status,

        [Parameter(Mandatory = $true, ParameterSetName = 'Body')]
        [object]
        $Body,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{
            'Name'   = @('body', 'name')
            'Tag'    = @('body', 'tag')
            'Status' = @('body', 'status')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['createPets']
            Cmdlet    = $PSCmdlet
        }
        if ($PSCmdlet.ParameterSetName -eq 'Body') {
            $tcsRequest['Body'] = $Body
        }
        else {
            $tcsRequest['Body'] = $tcsValues['body']
        }
        $tcsRequest['ContentType'] = 'application/json'
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        $tcsTarget = '/pets'
        foreach ($tcsKey in @($tcsValues['path'].Keys)) {
            $tcsTarget = $tcsTarget.Replace('{' + $tcsKey + '}', [string]$tcsValues['path'][$tcsKey])
        }
        if (-not $PSCmdlet.ShouldProcess($tcsTarget, 'POST')) {
            return
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
