function Remove-PetStorePet {
    <#
    .SYNOPSIS
        Delete a pet

    .DESCRIPTION
        Delete a pet

        Calls the 'deletePet' operation (DELETE /pets/{petId}).

        This operation is deprecated.

    .PARAMETER PetId
        The 'petId' path parameter.

    .PARAMETER ApiKey
        The 'api_key' header parameter.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Remove-PetStorePet -PetId 'example'

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: deletePet (DELETE /pets/{petId})
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        This operation is deprecated and may be removed from the API.
    #>
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
    param(
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string]
        $PetId,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [Alias('api_key')]
        [string]
        $ApiKey,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{
            'PetId'  = @('path', 'petId')
            'ApiKey' = @('header', 'api_key')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['deletePet']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['PathParameters'] = $tcsValues['path']
        $tcsRequest['HeaderParameters'] = $tcsValues['header']
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        $tcsTarget = '/pets/{petId}'
        foreach ($tcsKey in @($tcsValues['path'].Keys)) {
            $tcsTarget = $tcsTarget.Replace('{' + $tcsKey + '}', [string]$tcsValues['path'][$tcsKey])
        }
        if (-not $PSCmdlet.ShouldProcess($tcsTarget, 'DELETE')) {
            return
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
