function Get-ShopReport {
    <#
    .SYNOPSIS
        Calls `GET /reports/{reportId}`.

    .DESCRIPTION
        Calls the `getReport` operation (`GET /reports/{reportId}`).

    .PARAMETER ReportId
        The `reportId` path parameter.

    .PARAMETER OutFile
        Saves the response content to this file and returns the file.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-ShopReport -ReportId 1

        Calls `GET /reports/{reportId}` with example values for the required parameters.

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: `getReport` (`GET /reports/{reportId}`)
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [long]
        $ReportId,

        [Parameter()]
        [string]
        $OutFile,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        # Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        $tcsParameterMap = @{
            'ReportId' = @('path', 'reportId')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['getReport']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['PathParameters'] = $tcsValues['path']
        if ($PSBoundParameters.ContainsKey('OutFile')) {
            $tcsRequest['OutFile'] = $OutFile
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
