function Get-ShopOrder {
    <#
    .SYNOPSIS
        List orders

    .DESCRIPTION
        List orders

        Calls the `listOrders` operation (`GET /orders`).

    .PARAMETER Since
        The `since` query parameter.

    .PARAMETER Status
        The `status` query parameter.

    .PARAMETER IncludeDeleted
        The `include_deleted` query parameter.

    .PARAMETER MinTotal
        The `min_total` query parameter.

    .PARAMETER All
        Follows the next-page links and returns the items of every page.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-ShopOrder

        Calls `GET /orders` and returns the items of the first page.

    .EXAMPLE
        Get-ShopOrder -All

        Requests the following pages as well and returns the items of every page.

    .OUTPUTS
        Shop.Order

    .NOTES
        Operation: `listOrders` (`GET /orders`)
        This command lists or searches: it can return more than one object.
    #>
    [CmdletBinding()]
    [OutputType('Shop.Order')]
    param(
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [datetime]
        $Since,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet('open', 'closed')]
        [string[]]
        $Status,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [Alias('include_deleted')]
        [switch]
        $IncludeDeleted,

        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [Alias('min_total')]
        [double]
        $MinTotal,

        [Parameter()]
        [switch]
        $All,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        # Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        $tcsParameterMap = @{
            'Since'          = @('query', 'since')
            'Status'         = @('query', 'status')
            'IncludeDeleted' = @('query', 'include_deleted')
            'MinTotal'       = @('query', 'min_total')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['listOrders']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['QueryParameters'] = $tcsValues['query']
        if ($PSBoundParameters.ContainsKey('All')) {
            $tcsRequest['All'] = $All
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
