function New-ShopOrder {
    <#
    .SYNOPSIS
        Place an order

    .DESCRIPTION
        Place an order

        Calls the 'createOrder' operation (POST /orders).

    .PARAMETER Quantity
        The 'quantity' property of the request body.

    .PARAMETER Total
        The 'total' property of the request body.

    .PARAMETER Rush
        The 'rush' property of the request body.

    .PARAMETER ShipDate
        The 'shipDate' property of the request body.

    .PARAMETER Note
        The 'note' property of the request body.

    .PARAMETER Labels
        The 'labels' property of the request body.

    .PARAMETER Address
        The 'address' property of the request body.

    .PARAMETER LineItems
        The 'line-items' property of the request body.

    .PARAMETER Body
        The whole request body (for example a hashtable or an object read from a file), instead of the individual body parameters.

    .PARAMETER ContentType
        The media type of the request body. Defaults to 'application/json'.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        New-ShopOrder

    .OUTPUTS
        Shop.Order

    .NOTES
        Operation: createOrder (POST /orders)
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
    #>
    [CmdletBinding(DefaultParameterSetName = 'Parameters', SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    [OutputType('Shop.Order')]
    param(
        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [ValidateSet('1', '5', '10')]
        [int]
        $Quantity,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [ValidateRange(0.0, 10000.5)]
        [double]
        $Total,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [switch]
        $Rush,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [datetime]
        $ShipDate,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [AllowNull()]
        [ValidatePattern('^[a-z ]*$', Options = 'None')]
        [string]
        $Note,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [ValidateCount(0, 5)]
        [string[]]
        $Labels,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [hashtable]
        $Address,

        [Parameter(ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [Alias('line-items')]
        [hashtable[]]
        $LineItems,

        [Parameter(ParameterSetName = 'Body')]
        [object]
        $Body,

        [Parameter()]
        [ValidateSet('application/json', 'application/x-www-form-urlencoded')]
        [string]
        $ContentType,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{
            'Quantity'  = @('body', 'quantity')
            'Total'     = @('body', 'total')
            'Rush'      = @('body', 'rush')
            'ShipDate'  = @('body', 'shipDate')
            'Note'      = @('body', 'note')
            'Labels'    = @('body', 'labels')
            'Address'   = @('body', 'address')
            'LineItems' = @('body', 'line-items')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['createOrder']
            Cmdlet    = $PSCmdlet
        }
        if ($PSCmdlet.ParameterSetName -eq 'Body') {
            $tcsRequest['Body'] = $Body
        }
        elseif ($tcsValues['body'].Count -gt 0) {
            $tcsRequest['Body'] = $tcsValues['body']
        }
        $tcsRequest['ContentType'] = 'application/json'
        if ($PSBoundParameters.ContainsKey('ContentType')) {
            $tcsRequest['ContentType'] = $ContentType
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        $tcsTarget = '/orders'
        foreach ($tcsKey in @($tcsValues['path'].Keys)) {
            $tcsTarget = $tcsTarget.Replace('{' + $tcsKey + '}', [string]$tcsValues['path'][$tcsKey])
        }
        if (-not $PSCmdlet.ShouldProcess($tcsTarget, 'POST')) {
            return
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
