function New-ShopBatch {
    <#
    .SYNOPSIS
        Calls `POST /batch`.

    .DESCRIPTION
        Calls the `createBatch` operation (`POST /batch`).

    .PARAMETER Body
        The request body.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        New-ShopBatch -Body @()

        Calls `POST /batch` with example values for the required parameters.

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: `createBatch` (`POST /batch`)
    #>
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    param(
        [Parameter(Mandatory = $true)]
        [object]
        $Body,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        # Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        $tcsParameterMap = @{}
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['createBatch']
            Cmdlet    = $PSCmdlet
        }
        if ($PSBoundParameters.ContainsKey('Body')) {
            $tcsRequest['Body'] = $Body
        }
        $tcsRequest['ContentType'] = 'application/json'
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        $tcsTarget = '/batch'
        foreach ($tcsKey in @($tcsValues['path'].Keys)) {
            $tcsTarget = $tcsTarget.Replace('{' + $tcsKey + '}', [string]$tcsValues['path'][$tcsKey])
        }
        if (-not $PSCmdlet.ShouldProcess($tcsTarget, 'POST')) {
            return
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
