@{
    RootModule           = 'Reserved.Names.psm1'
    ModuleVersion        = '0.1.0'
    GUID                 = '99bc1b59-3bee-5bdc-aaf3-07551209c6ac'
    Author               = 'tcs.openapi'
    Copyright            = '(c) tcs.openapi. All rights reserved.'
    Description          = 'PowerShell commands for Reserved Names API (API version 2.1), generated by tcs.openapi.'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    RequiredModules      = @(
        @{ ModuleName = 'tcs.openapi'; ModuleVersion = '0.2.0' }
    )
    FunctionsToExport    = @(
        'Get-Gadget',
        'Get-Metadata',
        'Get-PetOwner',
        'Get-PetOwnerByPetId',
        'Get-ReservedNamesContext',
        'Get-StockItem',
        'New-User',
        'Remove-ReservedNamesContext',
        'Set-ReservedNamesContext',
        'Set-Thing',
        'Set-ThingPut',
        'Update-StockItem'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags = @('OpenAPI', 'REST', 'API', 'tcs.openapi')
        }
    }
}
