function Get-PetStoreInventory {
    <#
    .SYNOPSIS
        Returns pet inventories by status

    .DESCRIPTION
        Returns pet inventories by status

        Calls the 'getInventory' operation (GET /store/inventory).

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-PetStoreInventory

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: getInventory (GET /store/inventory)
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
    #>
    [CmdletBinding()]
    param(
        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{}
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['getInventory']
            Cmdlet    = $PSCmdlet
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
