@{
    RootModule           = 'Shop.psm1'
    ModuleVersion        = '0.1.0'
    GUID                 = '7de8316e-6bd7-5b33-9c5c-ec4aa938212e'
    Author               = 'tcs.openapi'
    Copyright            = '(c) tcs.openapi. All rights reserved.'
    Description          = 'PowerShell commands for Bodies API (API version 3.0), generated by tcs.openapi.'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    RequiredModules      = @(
        @{ ModuleName = 'tcs.openapi'; ModuleVersion = '0.2.0' }
    )
    FunctionsToExport    = @(
        'Get-ShopContext',
        'Get-ShopDownloadFile',
        'Get-ShopOrder',
        'Get-ShopPublicStatus',
        'Get-ShopReport',
        'New-ShopBatch',
        'New-ShopNote',
        'New-ShopOrder',
        'New-ShopUploadFile',
        'Remove-ShopContext',
        'Send-ShopEvent',
        'Set-ShopContext',
        'Set-ShopFileContent',
        'Submit-ShopForm'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags = @('OpenAPI', 'REST', 'API', 'tcs.openapi')
        }
    }
}
