function Get-ShopPublicStatus {
    <#
    .SYNOPSIS
        Calls `GET /public/status`.

    .DESCRIPTION
        Calls the `getPublicStatus` operation (`GET /public/status`).

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-ShopPublicStatus

        Calls `GET /public/status`.

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: `getPublicStatus` (`GET /public/status`)
    #>
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseSingularNouns', '', Justification = 'The noun comes from the API and has no singular form.')]
    [CmdletBinding()]
    param(
        [Parameter()]
        [switch]
        $Raw
    )

    process {
        # Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        $tcsParameterMap = @{}
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['getPublicStatus']
            Cmdlet    = $PSCmdlet
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
