function New-User {
    <#
    .SYNOPSIS
        Calls `POST /users`.

    .DESCRIPTION
        Calls the `createUser` operation (`POST /users`).

    .PARAMETER Username
        The `username` property of the request body.

    .PARAMETER Password
        The `password` property of the request body.

    .PARAMETER Body
        The whole request body (for example a hashtable or an object read from a file), instead of the individual body parameters.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        New-User -Username 'example' -Password 'example'

        Calls `POST /users` with example values for the required parameters.

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: `createUser` (`POST /users`)
    #>
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', '', Justification = 'The API takes this value as plain text.')]
    [CmdletBinding(DefaultParameterSetName = 'Parameters', SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    param(
        [Parameter(Mandatory = $true, ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [string]
        $Username,

        [Parameter(Mandatory = $true, ParameterSetName = 'Parameters', ValueFromPipelineByPropertyName = $true)]
        [string]
        $Password,

        [Parameter(Mandatory = $true, ParameterSetName = 'Body')]
        [object]
        $Body,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        # Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
        $tcsParameterMap = @{
            'Username' = @('body', 'username')
            'Password' = @('body', 'password')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['createUser']
            Cmdlet    = $PSCmdlet
        }
        if ($PSCmdlet.ParameterSetName -eq 'Body') {
            $tcsRequest['Body'] = $Body
        }
        else {
            $tcsRequest['Body'] = $tcsValues['body']
        }
        $tcsRequest['ContentType'] = 'application/json'
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        $tcsTarget = '/users'
        foreach ($tcsKey in @($tcsValues['path'].Keys)) {
            $tcsTarget = $tcsTarget.Replace('{' + $tcsKey + '}', [string]$tcsValues['path'][$tcsKey])
        }
        if (-not $PSCmdlet.ShouldProcess($tcsTarget, 'POST')) {
            return
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
