# Generated by tcs.openapi 0.3.1. Do not edit this file: regenerate the module instead,
# and put your own changes in Overrides.ps1 (it is never overwritten).

# The service name used for the connection context (Set-PetStoreContext) and in error ids
$script:TcsOpenApiService = 'PetStore'

# Operation metadata for Invoke-OpenApiRequest, keyed by operationId (case-sensitive)
$script:TcsOpenApiOperations = Microsoft.PowerShell.Utility\New-Object -TypeName System.Collections.Hashtable -ArgumentList ([System.StringComparer]::Ordinal)
$tcsOperationsPath = Microsoft.PowerShell.Management\Join-Path -Path (Microsoft.PowerShell.Management\Join-Path -Path $PSScriptRoot -ChildPath 'OpenApi') -ChildPath 'operations.json'
$tcsOperations = Microsoft.PowerShell.Utility\ConvertFrom-Json -InputObject ([System.IO.File]::ReadAllText($tcsOperationsPath))
foreach ($tcsOperation in $tcsOperations) {
    $tcsOperation.PSObject.TypeNames.Insert(0, 'Tcs.OpenApi.OperationMetadata')
    $script:TcsOpenApiOperations[$tcsOperation.OperationId] = $tcsOperation
}

# Cmdlets are module-qualified because a generated command may have the same name.
# Generated commands, then Overrides.ps1: a function defined there replaces the generated one
$tcsPublicPath = Microsoft.PowerShell.Management\Join-Path -Path $PSScriptRoot -ChildPath 'Public'
$tcsPublicFiles = @(Microsoft.PowerShell.Management\Get-ChildItem -Path $tcsPublicPath -Filter '*.ps1' -Recurse -File -ErrorAction SilentlyContinue | Microsoft.PowerShell.Utility\Sort-Object -Property FullName)
foreach ($tcsFile in $tcsPublicFiles) {
    . $tcsFile.FullName
}
$tcsOverridesPath = Microsoft.PowerShell.Management\Join-Path -Path $PSScriptRoot -ChildPath 'Overrides.ps1'
if (Microsoft.PowerShell.Management\Test-Path -LiteralPath $tcsOverridesPath) {
    . $tcsOverridesPath
}
