@{
    RootModule           = 'PetStore.psm1'
    ModuleVersion        = '0.1.0'
    GUID                 = 'bdeb8424-598e-5569-aa59-e719b841e866'
    Author               = 'tcs.openapi'
    Copyright            = '(c) tcs.openapi. All rights reserved.'
    Description          = 'PowerShell commands for Swagger Petstore (API version 1.0.0), generated by tcs.openapi.'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    RequiredModules      = @(
        @{ ModuleName = 'tcs.openapi'; ModuleVersion = '0.2.2' }
    )
    FunctionsToExport    = @(
        'Get-PetStoreContext',
        'Get-PetStoreHealth',
        'Get-PetStoreInventory',
        'Get-PetStorePet',
        'Get-PetStorePetById',
        'Get-PetStorePetPhoto',
        'Measure-PetStatistic',
        'New-PetStorePet',
        'Remove-PetStoreContext',
        'Remove-PetStorePet',
        'Set-PetStoreContext',
        'Set-PetStorePet'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags = @('OpenAPI', 'REST', 'API', 'tcs.openapi')
        }
    }
}
