function Get-ShopDownloadFile {
    <#
    .SYNOPSIS
        Calls GET /files/{fileId}.

    .DESCRIPTION
        Calls the 'downloadFile' operation (GET /files/{fileId}).

    .PARAMETER FileId
        The 'fileId' path parameter.

    .PARAMETER OutFile
        Saves the response content to this file and returns the file.

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Get-ShopDownloadFile -FileId 'example'

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: downloadFile (GET /files/{fileId})
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [Alias('Id')]
        [string]
        $FileId,

        [Parameter()]
        [string]
        $OutFile,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{
            'FileId' = @('path', 'fileId')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['downloadFile']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['PathParameters'] = $tcsValues['path']
        if ($PSBoundParameters.ContainsKey('OutFile')) {
            $tcsRequest['OutFile'] = $OutFile
        }
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
