function Set-ShopFileContent {
    <#
    .SYNOPSIS
        Calls PUT /files/{fileId}/content.

    .DESCRIPTION
        Calls the 'putFileContent' operation (PUT /files/{fileId}/content).

    .PARAMETER FileId
        The 'fileId' path parameter.

    .PARAMETER Body
        The request body. A [byte[]], a [System.IO.Stream] or a [System.IO.FileInfo].

    .PARAMETER Raw
        Returns the raw response (StatusCode, Headers and Content) instead of the parsed content.

    .EXAMPLE
        Set-ShopFileContent -FileId 'example' -Body (Get-Item -Path './file.bin')

    .OUTPUTS
        System.Management.Automation.PSObject

    .NOTES
        Operation: putFileContent (PUT /files/{fileId}/content)
        Generated by tcs.openapi. Do not edit: put changes in Overrides.ps1.
    #>
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    param(
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [string]
        $FileId,

        [Parameter(Mandatory = $true)]
        [object]
        $Body,

        [Parameter()]
        [switch]
        $Raw
    )

    process {
        $tcsParameterMap = @{
            'FileId' = @('path', 'fileId')
        }
        $tcsValues = @{ 'path' = @{}; 'query' = @{}; 'header' = @{}; 'cookie' = @{}; 'body' = @{} }
        foreach ($tcsName in @($tcsParameterMap.Keys)) {
            if ($PSBoundParameters.ContainsKey($tcsName)) {
                $tcsValue = $PSBoundParameters[$tcsName]
                if ($tcsValue -is [System.Management.Automation.SwitchParameter]) {
                    $tcsValue = $tcsValue.IsPresent
                }
                $tcsValues[$tcsParameterMap[$tcsName][0]][$tcsParameterMap[$tcsName][1]] = $tcsValue
            }
        }

        $tcsRequest = @{
            Service   = $script:TcsOpenApiService
            Operation = $script:TcsOpenApiOperations['putFileContent']
            Cmdlet    = $PSCmdlet
        }
        $tcsRequest['PathParameters'] = $tcsValues['path']
        if ($PSBoundParameters.ContainsKey('Body')) {
            $tcsRequest['Body'] = $Body
        }
        $tcsRequest['ContentType'] = 'application/octet-stream'
        if ($PSBoundParameters.ContainsKey('Raw')) {
            $tcsRequest['Raw'] = $Raw
        }
        $tcsTarget = '/files/{fileId}/content'
        foreach ($tcsKey in @($tcsValues['path'].Keys)) {
            $tcsTarget = $tcsTarget.Replace('{' + $tcsKey + '}', [string]$tcsValues['path'][$tcsKey])
        }
        if (-not $PSCmdlet.ShouldProcess($tcsTarget, 'PUT')) {
            return
        }
        Invoke-OpenApiRequest @tcsRequest
    }
}
